id: I278F4709
legacy_id: P000493
ocr_import_info:
  bdrc_scan_id: W00EGS1016947
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T13:20:33'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T10:49:25.457930+00:00'
last_modified: 2022-08-29 18:50:13.125920
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1016947
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1016947
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། པདྨ་ལུང་རྟོགས་རྒྱ་མཚོ།
  author: པདྨ་ལུང་རྟོགས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.7148418088201262
  ocr_word_median_confidence_index: 0.7900000214576721
quality: null
bases:
  I01JW198:
    source_metadata:
      id: http://purl.bdrc.io/resource/I01JW198
      total_pages: 534
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I01JW198.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7148418088201262
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
