id: P000493
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00EGS1016947
  title: གསུང་འབུམ། པདྨ་ལུང་རྟོགས་རྒྱ་མཚོ
  author: ''
  volumes:
    2bfb0070dcd14af3a74002bd223f1863:
      image_group_id: I01JW198
      title: Volume 1 of gsung 'bum/_pad+ma lung rtogs rgya mtsho
      volume_number: 1
      total_pages: 534
      base_file: v001.txt
